import Player from '#models/player'
import { BaseSeeder } from '@adonisjs/lucid/seeders'

export default class extends BaseSeeder {
  async run() {
    await Player.createMany([
      { nom: 'VERGNE', prenom: 'Marcel' },
      { nom: 'GODART', prenom: 'Stéphane' },
      { nom: 'RABREAU', prenom: 'Franck' },
      { nom: 'NAUD', prenom: 'Sophie' },
      { nom: 'GUITTONEAU', prenom: 'Lesly' },
      { nom: 'DONNY', prenom: 'Lucas' },
      { nom: 'CHOUIN', prenom: 'Teddy' },
      { nom: 'PAJOT', prenom: 'John' },
      { nom: 'BOURDET', prenom: 'Fabien' },
      { nom: 'PROTEAU', prenom: 'Thierry' },
      { nom: 'GIRAUDET', prenom: 'Christian' },
      { nom: 'MICHAUD', prenom: 'Jean-Marc' },
      { nom: 'BETHUYS', prenom: 'Mickael' },
      { nom: 'VOYEAU', prenom: 'Nicolas' },
      { nom: 'RONDEAU', prenom: 'Olivier' },
      { nom: 'ROBIN', prenom: 'Ludovic' },
      { nom: 'BARRETEAU', prenom: 'Tanguy' },
      { nom: 'FAVREAU', prenom: 'Emrick' },
      { nom: 'GUILLOTEAU', prenom: 'David' },
      { nom: 'PONTOIZEAU', prenom: 'Stéphane' },
      { nom: 'MOIZEAU', prenom: 'Michel' },
      { nom: 'AUGIZEAU', prenom: 'Corentin' },
      { nom: 'VERGNE', prenom: 'Jérôme' },
      { nom: 'FERRE', prenom: 'Yann' },
      { nom: 'NAULLEAU', prenom: 'Pascal' },
      { nom: 'RAFFIN', prenom: 'Vincent' },
      { nom: 'GUITTONEAU', prenom: 'Cédric' },
      { nom: 'GIRAUDET', prenom: 'Damien' },
      { nom: 'PORCHET', prenom: 'Jean Noël' },
      { nom: 'JUTARD', prenom: 'Corentin' },
      { nom: 'REMAUD', prenom: 'Brice' },
      { nom: 'DUFIEF', prenom: 'Gaëtan' },
      { nom: 'MOREAU', prenom: 'Yann' },
      { nom: "PROD'HOMME", prenom: 'Hugo' },
      { nom: 'GUIBERT', prenom: 'Daniel' },
      { nom: 'VERGNE', prenom: 'Sébastien' },
      { nom: 'GUILLOTEAU', prenom: 'Kévin' },
      { nom: 'BERNARD', prenom: 'Sullivan' },
      { nom: 'PADIOLLEAU', prenom: 'Romain' },
      { nom: 'DONNY', prenom: 'Julien' },
      { nom: 'BOURDET', prenom: 'Mickaël' },
      { nom: 'BURGAUD', prenom: 'Marion' },
      { nom: 'VAUGRENARD', prenom: 'Antoine' },
      { nom: 'DABRETEAU', prenom: 'Jacky' },
      { nom: 'GIRAUDET', prenom: 'Stéphane' },
      { nom: 'BOUCARD', prenom: 'Antonio' },
    ])
  }
}
